// stage-2/invoice-management-app/src/components/ui/input.tsx
import * as React from "react";

import { cn } from "@/lib/utils";

function Input({ className, type, ...props }: React.ComponentProps<"input">) {
  return (
    <input
      type={type}
      data-slot="input"
      className={cn(
        "h-8 min-w-0 px-2.5py-1 text-base transition-colors outline-none file:inline-flex file:h-6 file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground disabled:pointer-events-none disabled:cursor-not-allowed disabled:bg-input/50 disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20 md:text-sm dark:disabled:bg-input/80 dark:aria-invalid:border-destructive/50 dark:aria-invalid:ring-destructive/40 flex w-full rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-invoice-card-dark px-4 py-2 text-invoice-text-primary dark:text-invoice-text-light placeholder-gray-400 dark:placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-invoice-primary focus:border-transparent",
        className,
      )}
      {...props}
    />
  );
}

export { Input };

// stage-5a/src/shared/components/ui/Input.vue
<template>
  <div class="w-full">
    <label
      v-if="label"
      :for="id"
      class="block text-sm font-medium text-text-base mb-2"
    >
      {{ label }}
      <span v-if="required" class="text-error">*</span>
    </label>

    <input
      :id="id"
      :type="type"
      :placeholder="placeholder"
      :required="required"
      :disabled="disabled"
      :value="modelValue"
      @input="
        $emit('update:modelValue', ($event.target as HTMLInputElement).value)
      "
      :class="[
        // Base styles
        'w-full px-4 py-2.5 rounded-lg',
        'border border-dark-border bg-dark-surface text-text-base',
        'placeholder:text-text-tertiary',
        'transition-all duration-200',

        // Focus states
        'focus:outline-none focus:ring-2 focus:ring-brand-primary focus:border-transparent',
        'focus:shadow-lg focus:shadow-brand-primary/10',

        // States
        'disabled:opacity-50 disabled:cursor-not-allowed',
        'hover:border-dark-border/60',

        // Error state
        error ? 'border-error ring-1 ring-error/30' : '',

        // Custom classes
        props.customClass,
      ]"
    />

    <p v-if="error" class="text-error text-sm mt-1">{{ error }}</p>
    <p v-if="hint" class="text-text-tertiary text-sm mt-1">{{ hint }}</p>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";

interface Props {
  modelValue?: string;
  type?: string;
  placeholder?: string;
  label?: string;
  error?: string;
  hint?: string;
  required?: boolean;
  disabled?: boolean;
  id?: string;
  customClass?: string;
}

const props = withDefaults(defineProps<Props>(), {
  type: "text",
  modelValue: "",
});

const emit = defineEmits<{
  "update:modelValue": [value: string];
}>();

const id = computed(
  () => props.id || `input-${Math.random().toString(36).substr(2, 9)}`,
);
</script>
